apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "test-disruption-probe.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test-disruption-probe.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "test-disruption-probe.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test-disruption-probe.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "test-disruption-probe.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "test-disruption-probe.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
