apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-disruption-probe.fullname" . }}
  labels:
    {{- include "test-disruption-probe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: http
  selector:
    {{- include "test-disruption-probe.selectorLabels" . | nindent 4 }}
