// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: disruptionprobe/v1/disruptionprobe.proto

package disruptionprobe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DisruptionProbeService_IsDisruptionAllowed_FullMethodName = "/disruptionprobe.v1.DisruptionProbeService/IsDisruptionAllowed"
)

// DisruptionProbeServiceClient is the client API for DisruptionProbeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The DisruptionProbe service definition.
type DisruptionProbeServiceClient interface {
	// Sends a IsDisruptionAllowed request
	IsDisruptionAllowed(ctx context.Context, in *IsDisruptionAllowedRequest, opts ...grpc.CallOption) (*IsDisruptionAllowedResponse, error)
}

type disruptionProbeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDisruptionProbeServiceClient(cc grpc.ClientConnInterface) DisruptionProbeServiceClient {
	return &disruptionProbeServiceClient{cc}
}

func (c *disruptionProbeServiceClient) IsDisruptionAllowed(ctx context.Context, in *IsDisruptionAllowedRequest, opts ...grpc.CallOption) (*IsDisruptionAllowedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsDisruptionAllowedResponse)
	err := c.cc.Invoke(ctx, DisruptionProbeService_IsDisruptionAllowed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisruptionProbeServiceServer is the server API for DisruptionProbeService service.
// All implementations must embed UnimplementedDisruptionProbeServiceServer
// for forward compatibility.
//
// The DisruptionProbe service definition.
type DisruptionProbeServiceServer interface {
	// Sends a IsDisruptionAllowed request
	IsDisruptionAllowed(context.Context, *IsDisruptionAllowedRequest) (*IsDisruptionAllowedResponse, error)
	mustEmbedUnimplementedDisruptionProbeServiceServer()
}

// UnimplementedDisruptionProbeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDisruptionProbeServiceServer struct{}

func (UnimplementedDisruptionProbeServiceServer) IsDisruptionAllowed(context.Context, *IsDisruptionAllowedRequest) (*IsDisruptionAllowedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsDisruptionAllowed not implemented")
}
func (UnimplementedDisruptionProbeServiceServer) mustEmbedUnimplementedDisruptionProbeServiceServer() {
}
func (UnimplementedDisruptionProbeServiceServer) testEmbeddedByValue() {}

// UnsafeDisruptionProbeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisruptionProbeServiceServer will
// result in compilation errors.
type UnsafeDisruptionProbeServiceServer interface {
	mustEmbedUnimplementedDisruptionProbeServiceServer()
}

func RegisterDisruptionProbeServiceServer(s grpc.ServiceRegistrar, srv DisruptionProbeServiceServer) {
	// If the following call pancis, it indicates UnimplementedDisruptionProbeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DisruptionProbeService_ServiceDesc, srv)
}

func _DisruptionProbeService_IsDisruptionAllowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsDisruptionAllowedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisruptionProbeServiceServer).IsDisruptionAllowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DisruptionProbeService_IsDisruptionAllowed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisruptionProbeServiceServer).IsDisruptionAllowed(ctx, req.(*IsDisruptionAllowedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DisruptionProbeService_ServiceDesc is the grpc.ServiceDesc for DisruptionProbeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DisruptionProbeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "disruptionprobe.v1.DisruptionProbeService",
	HandlerType: (*DisruptionProbeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsDisruptionAllowed",
			Handler:    _DisruptionProbeService_IsDisruptionAllowed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "disruptionprobe/v1/disruptionprobe.proto",
}
