{{- if .Values.certificates.webhook.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "x-pdb.fullname" . }}-webhook-cert
  namespace: {{ include "x-pdb.namespace" . }}
  labels:
    {{- include "x-pdb.webhookLabels" . | nindent 4 }}
spec:
  {{- if .Values.certificates.webhook.certManager.injectFromSecret }}
  secretTemplate:
    annotations:
      cert-manager.io/allow-direct-injection: "true"
  {{- end }}
  dnsNames:
  - {{ include "x-pdb.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
  - {{ include "x-pdb.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    {{- toYaml .Values.certificates.webhook.certManager.issuerRef | nindent 4 }}
  secretName: {{ include "x-pdb.fullname" . }}-webhook-cert
  renewBefore: {{ .Values.certificates.webhook.certManager.renewBefore }}
  duration: {{ .Values.certificates.webhook.certManager.duration }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
{{- end }}

{{- if .Values.certificates.state.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "x-pdb.fullname" . }}-state-cert
  namespace: {{ include "x-pdb.namespace" . }}
  labels:
    {{- include "x-pdb.stateLabels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "x-pdb.stateServiceName" . }}
    - {{ include "x-pdb.stateServiceName" . }}.{{ include "x-pdb.namespace" . }}
    - {{ include "x-pdb.stateServiceName" . }}.{{ include "x-pdb.namespace" . }}.svc
    - {{ include "x-pdb.stateServiceName" . }}.{{ include "x-pdb.namespace" . }}.svc.cluster.local
    {{- range $name:= .Values.certificates.state.certManager.dnsNames }}
    - {{ $name }}
    {{- end }}
  ipAddresses:
    {{- toYaml .Values.certificates.state.certManager.ipAddresses | nindent 4 }}
  issuerRef:
    {{- toYaml .Values.certificates.state.certManager.issuerRef | nindent 4 }}
  secretName: {{ include "x-pdb.fullname" . }}-state-cert
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: {{ .Values.certificates.state.certManager.renewBefore }}
  duration: {{ .Values.certificates.state.certManager.duration }}
  usages:
    - digital signature
    - key encipherment
    - client auth
    - server auth
{{- end }}
