apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "x-pdb.fullname" .) .Values.service.webhook.nameOverride }}
  namespace: {{ include "x-pdb.namespace" . }}
  labels:
    {{- include "x-pdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.webhook.type }}
  ports:
    - port: 443
      name: webhook
      protocol: TCP
      targetPort: webhook
      {{- with .Values.service.webhook.nodePort }}
      nodePort: {{ . }}
      {{- end }}
    - port: {{ .Values.serviceMonitor.service.port }}
      name: metrics
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "x-pdb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-controller" (include "x-pdb.fullname" .)) .Values.service.controller.nameOverride }}
  namespace: {{ include "x-pdb.namespace" . }}
  labels:
    {{- include "x-pdb.labels" . | nindent 4 }}
  {{- with .Values.service.controller.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.controller.type }}
  {{- with .Values.service.controller.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - port: 443
      name: state
      protocol: TCP
      targetPort: controller
      {{- with .Values.service.controller.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "x-pdb.selectorLabels" . | nindent 4 }}
