{{- if .Values.webhook.enabled -}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "x-pdb.fullname" . }}-pod-deletion-validation
  annotations:
{{- if .Values.webhook.tls.certManager.enabled }}
    {{- if .Values.webhook.tls.certManager.injectFromSecret }}
    cert-manager.io/inject-ca-from-secret: {{ .Release.Namespace }}/{{ include "x-pdb.fullname" . }}-webhook-cert
    {{- else }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "x-pdb.fullname" . }}-webhook-cert
    {{- end }}
{{- end }}
webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      service:
        name: {{ include "x-pdb.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate
{{- if .Values.webhook.tls.cert.enabled }}
      caBundle: {{ .Values.webhook.tls.cert.caBundle | quote }}
{{- end }}
    failurePolicy: Fail
    name: deletion.x-pdb.form3.tech
{{- if .Values.webhook.namespaceSelector }}
    namespaceSelector:
      {{- toYaml .Values.webhook.namespaceSelector | nindent 6 -}}
{{- end }}
    rules:
    - apiGroups:
        - ""
      apiVersions:
        - "v1"
      resources:
        - "pods"
      operations:
        - "DELETE"
    sideEffects: None
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
  - admissionReviewVersions:
    - v1
    clientConfig:
      service:
        name: {{ include "x-pdb.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate
{{- if .Values.webhook.tls.cert.enabled }}
      caBundle: {{ .Values.webhook.tls.cert.caBundle | quote }}
{{- end }}
    failurePolicy: Fail
    name: eviction.x-pdb.form3.tech
{{- if .Values.webhook.namespaceSelector }}
    namespaceSelector:
      {{- toYaml .Values.webhook.namespaceSelector | nindent 6 -}}
{{- end }}
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - "v1"
      resources:
      - "pods/eviction"
      operations:
      - "CREATE"
    sideEffects: None
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
{{- end -}}