webhook:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  image:
    tag: "latest"
  extraArgs:
  - --zap-stacktrace-level=panic
  automountServiceAccountToken: true
state:
  image:
    tag: "latest"
  extraArgs:
  - --zap-stacktrace-level=panic
  # remoteEndpoints computed dynamically via install-xpdb.sh
  service:
    type: LoadBalancer
    # loadBalancerIP computed dynamically via install-xpdb.sh
  automountServiceAccountToken: false
certificates:
  state:
    certManager:
      enabled: true
      issuerRef:
        kind: ClusterIssuer
        name: cluster-issuer
      # ipAddresses computed dynamically via install-xpdb.sh
  webhook:
    certManager:
      enabled: true
      issuerRef:
        kind: ClusterIssuer
        name: cluster-issuer
