name: Publish Chart

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      CHART_DIR: helm
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: v3.12.0
      - name: Login to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package chart
        id: package
        run: |
          helm package ${{ env.CHART_DIR }}
          echo "chart_file=$(ls *.tgz)" >> $GITHUB_OUTPUT
      - name: Push chart to GHCR
        id: push
        run: |
          helm push ${{ env.CHART_FILE }} oci://${{ env.REGISTRY }}/${{ github.repository }}/charts
          DIGEST=$(helm inspect chart oci://${{ env.REGISTRY }}/${{ github.repository }}/charts/${{ steps.package.outputs.chart_file }} --show-values=false | sha256sum | cut -d' ' -f1)
          echo "image=${{ env.REGISTRY }}/${{ github.repository }}/charts/${{ steps.package.outputs.chart_file }}" >> $GITHUB_OUTPUT
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
      - name: Install Cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
      - name: Sign Helm Chart Image
        run: |
          cosign sign --yes "oci://${{ env.REGISTRY }}/${{ github.repository }}/charts/${{ env.CHART_FILE }}@${{ steps.push.outputs.digest }}"

  ghcr-provenance:
    needs: [publish-chart]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    if: startsWith(github.ref, 'refs/tags/v')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@5a775b367a56d5bd118a224a811bba288150a563 # v2.0.0
    with:
      image: ${{ needs.publish-chart.outputs.image }}
      digest: ${{ needs.publish-chart.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
