name: Publish Chart

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:
    inputs:
      tag:
        description: 'image tag prefix'
        default: 'rc'
        required: true

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      CHART_DIR: helm
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package chart
        run: |
          helm package ${{ env.CHART_DIR }}
          echo "CHART_FILE=$(ls *.tgz)" >> $GITHUB_ENV
      - name: Push chart to GHCR
        run: |
          helm push ${{ env.CHART_FILE }} oci://${{ env.REGISTRY }}/${{ github.repository }}/charts
